# Generated by Django 6.0 on 2026-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default="Hi, I'm Dipak Bhatt", max_length=100)),
                ('bio_1', models.TextField()),
                ('bio_2', models.TextField()),
            ],
        ),
    ]
