# Generated by Django 6.0 on 2026-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=50, help_text='Enter skill proficiency in % (0-100)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='skills/icons/')),
            ],
        ),
    ]
